apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: feed
  name: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  strategy: {}
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - image: saiicharan/feed
        name: feed
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
status: {}